const colors = {
  light: {
    text: "#1e2533",
    tint: "#2563eb",
    background: "#fafafa",
    foreground: "#1e2533",
    card: "#ffffff",
    cardForeground: "#1e2533",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    secondary: "#f1f3f7",
    secondaryForeground: "#1e2533",
    muted: "#f1f3f7",
    mutedForeground: "#566478",
    accent: "#f59e0b",
    accentForeground: "#ffffff",
    destructive: "#f04545",
    destructiveForeground: "#ffffff",
    border: "#dce2ed",
    input: "#dce2ed",
  },
  dark: {
    text: "#dde2eb",
    tint: "#2563eb",
    background: "#060d1a",
    foreground: "#dde2eb",
    card: "#0c1523",
    cardForeground: "#dde2eb",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    secondary: "#1a2433",
    secondaryForeground: "#dde2eb",
    muted: "#1a2433",
    mutedForeground: "#8696aa",
    accent: "#f59e0b",
    accentForeground: "#ffffff",
    destructive: "#f04545",
    destructiveForeground: "#ffffff",
    border: "#1a2433",
    input: "#1a2433",
  },
  radius: 12,
};

export default colors;
